server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: evento
          uri: lb://evento/
          predicates:
            - Path=/evento/**
        - id: ventaentradas
          uri: lb://ventaentradas/
          predicates:
            - Path=/ventaentradas/**
